repos:
  - repo: local
    hooks:
      - id: run-latex-suite-table
        name: Run Latex Suite Table Script
        entry: .\latex_suite_table.py .\snippets.txt
        language: system
        files: ^snippets\.txt$